import type { SettingsCategory, SettingDefinition, SettingValue } from "./types";

// ============================================
// Default Values & Category Definitions
// ============================================

export const DEFAULT_SETTINGS: Record<string, SettingValue> = {
  // General
  platform_name: "ArtForgeLab",
  platform_description: "Intellectual Property Rights Management System for Digital Art",
  support_email: "support@artforgelab.com",
  default_timezone: "UTC",
  default_language: "en",
  footer_copyright: "© 2026 ArtForgeLab. All rights reserved.",

  // Artwork
  maximum_upload_size: 50,
  allowed_file_types: ["jpg", "jpeg", "png", "gif", "webp", "svg"],
  maximum_artwork_dimensions: 4096,
  maximum_number_of_genres: 5,
  require_description: true,
  require_evidence: false,
  automatic_registration: true,
  enable_artwork_visibility: true,
  default_visibility: "public",
  enable_nsfw_detection: true,
  nsfw_default: false,

  // Similarity Detection
  similarity_threshold: 80,
  manual_review_threshold: 60,
  automatic_approval_threshold: 30,
  maximum_similarity_matches: 20,
  minimum_confidence_score: 50,
  enable_automatic_scanning: true,
  enable_external_search: true,
  similarity_scan_timeout: 60,
  retry_attempts: 3,
  enable_duplicate_file_detection: true,

  // Manual Review
  enable_manual_review: true,
  require_review_above: 60,
  automatically_hide_above: 90,
  require_admin_approval: true,
  auto_notify_artist: true,
  auto_notify_admin: true,
  allow_false_positive_override: true,
  maximum_review_days: 14,

  // Blockchain
  default_chain: "polygon-amoy",
  enable_blockchain_registration: true,
  retry_failed_transactions: true,
  maximum_retry_count: 3,
  auto_register_after_upload: true,
  display_blockchain_badge: true,
  verification_timeout: 120,
  explorer_base_url: "https://amoy.polygonscan.com",

  // Community
  enable_community_feed: true,
  enable_upvotes: true,
  enable_downvotes: true,
  enable_comments: true,
  enable_artwork_sharing: true,
  enable_artist_verification_badge: true,
  allow_anonymous_viewing: true,
  enable_nsfw_content: true,
  minimum_reputation_required: 0,

  // Reports
  enable_reporting: true,
  maximum_reports_per_day: 10,
  auto_assign_reports: true,
  auto_escalate: true,
  escalation_threshold: 3,
  default_report_status: "open",
  maximum_evidence_files: 5,
  maximum_evidence_size: 20,
  require_explanation: true,

  // Notifications
  enable_email_notifications: true,
  enable_in_app_notifications: true,
  notify_on_reports: true,
  notify_on_blockchain_success: true,
  notify_on_similarity_detection: true,
  notify_on_manual_review: true,
  notify_on_report_resolution: true,
  notification_retention_days: 90,

  // Security
  maximum_login_attempts: 5,
  session_timeout: 3600,
  password_reset_expiration: 3600,
  require_verified_email: true,
  allowed_origins: [],
  enable_audit_logs: true,
  admin_session_timeout: 1800,

  // Maintenance
  maintenance_mode: false,
  maintenance_message: "We are currently performing scheduled maintenance. Please check back shortly.",
  scheduled_maintenance: false,
  allow_admin_login_during_maintenance: true,
  display_countdown: false,
};

// ============================================
// Setting Definitions by Category
// ============================================

export const SETTINGS_CATEGORIES: SettingsCategory[] = [
  {
    id: "general",
    label: "General",
    icon: "Settings2",
    description: "Platform information and branding configuration",
    settings: [
      {
        key: "platform_name",
        label: "Platform Name",
        description: "The display name of the platform shown to all users",
        type: "text",
        defaultValue: "ArtForgeLab",
      },
      {
        key: "platform_description",
        label: "Platform Description",
        description: "A short description of the platform used in meta tags and headers",
        type: "textarea",
        defaultValue: "Intellectual Property Rights Management System for Digital Art",
      },
      {
        key: "support_email",
        label: "Support Email",
        description: "Email address displayed to users for support inquiries",
        type: "email",
        defaultValue: "support@artforgelab.com",
        placeholder: "support@example.com",
      },
      {
        key: "default_timezone",
        label: "Default Time Zone",
        description: "Default timezone for date and time displays across the platform",
        type: "select",
        defaultValue: "UTC",
        options: [
          { label: "UTC (Coordinated Universal Time)", value: "UTC" },
          { label: "America/New_York (Eastern)", value: "America/New_York" },
          { label: "America/Chicago (Central)", value: "America/Chicago" },
          { label: "America/Denver (Mountain)", value: "America/Denver" },
          { label: "America/Los_Angeles (Pacific)", value: "America/Los_Angeles" },
          { label: "Europe/London (GMT)", value: "Europe/London" },
          { label: "Europe/Paris (CET)", value: "Europe/Paris" },
          { label: "Asia/Tokyo (JST)", value: "Asia/Tokyo" },
          { label: "Asia/Shanghai (CST)", value: "Asia/Shanghai" },
          { label: "Asia/Manila (PST)", value: "Asia/Manila" },
          { label: "Australia/Sydney (AEST)", value: "Australia/Sydney" },
        ],
      },
      {
        key: "default_language",
        label: "Default Language",
        description: "Default language locale for the platform interface",
        type: "select",
        defaultValue: "en",
        options: [
          { label: "English", value: "en" },
          { label: "Spanish", value: "es" },
          { label: "French", value: "fr" },
          { label: "German", value: "de" },
          { label: "Japanese", value: "ja" },
          { label: "Chinese", value: "zh" },
          { label: "Filipino", value: "fil" },
        ],
      },
      {
        key: "footer_copyright",
        label: "Footer Copyright",
        description: "Copyright notice displayed in the footer of all pages",
        type: "text",
        defaultValue: "© 2026 ArtForgeLab. All rights reserved.",
      },
    ],
  },
  {
    id: "artwork",
    label: "Artwork",
    icon: "ImageIcon",
    description: "Artwork upload and registration settings",
    settings: [
      {
        key: "maximum_upload_size",
        label: "Maximum Upload Size",
        description: "Maximum file upload size in megabytes. Larger files will be rejected",
        type: "number",
        defaultValue: 50,
        min: 1,
        max: 500,
        unit: "MB",
        badge: "recommended",
      },
      {
        key: "allowed_file_types",
        label: "Allowed File Types",
        description: "Comma-separated list of allowed file extensions for artwork uploads",
        type: "tags",
        defaultValue: ["jpg", "jpeg", "png", "gif", "webp", "svg"],
      },
      {
        key: "maximum_artwork_dimensions",
        label: "Maximum Artwork Dimensions",
        description: "Maximum width or height of artwork images in pixels",
        type: "number",
        defaultValue: 4096,
        min: 512,
        max: 16384,
        unit: "px",
      },
      {
        key: "maximum_number_of_genres",
        label: "Maximum Number of Genres",
        description: "Maximum number of genres an artwork can be tagged with",
        type: "number",
        defaultValue: 5,
        min: 1,
        max: 20,
      },
      {
        key: "require_description",
        label: "Require Description",
        description: "Whether artwork description is required during upload",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "require_evidence",
        label: "Require Evidence",
        description: "Whether evidence files are required during artwork registration",
        type: "toggle",
        defaultValue: false,
      },
      {
        key: "automatic_registration",
        label: "Automatic Registration",
        description: "Whether artworks are automatically registered upon upload",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_artwork_visibility",
        label: "Enable Artwork Visibility",
        description: "Whether artists can control artwork visibility settings (public, private, unlisted)",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "default_visibility",
        label: "Default Visibility",
        description: "Default visibility for new artworks",
        type: "select",
        defaultValue: "public",
        options: [
          { label: "Public", value: "public" },
          { label: "Private", value: "private" },
          { label: "Unlisted", value: "unlisted" },
        ],
      },
      {
        key: "enable_nsfw_detection",
        label: "Enable NSFW Detection",
        description: "Whether NSFW content detection is enabled for artwork uploads",
        type: "toggle",
        defaultValue: true,
        badge: "recommended",
      },
      {
        key: "nsfw_default",
        label: "NSFW Default",
        description: "Default NSFW flag for artworks when detection is inconclusive",
        type: "toggle",
        defaultValue: false,
      },
    ],
  },
  {
    id: "similarity",
    label: "Similarity Detection",
    icon: "SearchIcon",
    description: "Plagiarism and similarity detection configuration",
    settings: [
      {
        key: "similarity_threshold",
        label: "Similarity Threshold",
        description: "Percentage threshold above which artworks are considered similar. Higher values are stricter",
        type: "slider",
        defaultValue: 80,
        min: 0,
        max: 100,
        step: 1,
        unit: "%",
        badge: "critical",
        requiresConfirmation: true,
        confirmationMessage: "Changing this value affects all future plagiarism scans. Continue?",
      },
      {
        key: "manual_review_threshold",
        label: "Manual Review Threshold",
        description: "Similarity percentage above which artworks are flagged for manual review by an admin",
        type: "slider",
        defaultValue: 60,
        min: 0,
        max: 100,
        step: 1,
        unit: "%",
      },
      {
        key: "automatic_approval_threshold",
        label: "Automatic Approval Threshold",
        description: "Similarity percentage below which artworks are automatically approved without review",
        type: "slider",
        defaultValue: 30,
        min: 0,
        max: 100,
        step: 1,
        unit: "%",
        requiresConfirmation: true,
        confirmationMessage: "This will bypass manual reviews for artworks below the threshold. Continue?",
      },
      {
        key: "maximum_similarity_matches",
        label: "Maximum Similarity Matches",
        description: "Maximum number of similar artwork matches to return per scan",
        type: "number",
        defaultValue: 20,
        min: 1,
        max: 100,
      },
      {
        key: "minimum_confidence_score",
        label: "Minimum Confidence Score",
        description: "Minimum confidence score for similarity matches to be considered valid",
        type: "slider",
        defaultValue: 50,
        min: 0,
        max: 100,
        step: 1,
        unit: "%",
      },
      {
        key: "enable_automatic_scanning",
        label: "Enable Automatic Scanning",
        description: "Whether similarity scanning runs automatically when artworks are uploaded",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_external_search",
        label: "Enable External Search",
        description: "Whether to search external sources and databases for similar artworks",
        type: "toggle",
        defaultValue: true,
        badge: "advanced",
      },
      {
        key: "similarity_scan_timeout",
        label: "Similarity Scan Timeout",
        description: "Maximum time in seconds for a similarity scan to complete before timing out",
        type: "number",
        defaultValue: 60,
        min: 10,
        max: 300,
        unit: "seconds",
      },
      {
        key: "retry_attempts",
        label: "Retry Attempts",
        description: "Number of retry attempts for failed similarity scans",
        type: "number",
        defaultValue: 3,
        min: 0,
        max: 10,
      },
      {
        key: "enable_duplicate_file_detection",
        label: "Enable Duplicate File Detection",
        description: "Whether to check for exact file hash duplicates during upload to prevent re-registration",
        type: "toggle",
        defaultValue: true,
      },
    ],
  },
  {
    id: "manual-review",
    label: "Manual Review",
    icon: "ShieldCheck",
    description: "Manual artwork review queue configuration",
    settings: [
      {
        key: "enable_manual_review",
        label: "Enable Manual Review",
        description: "Whether the manual review queue is enabled for artworks flagged by similarity detection",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "require_review_above",
        label: "Require Review Above",
        description: "Similarity percentage above which manual review is required before publishing",
        type: "slider",
        defaultValue: 60,
        min: 0,
        max: 100,
        step: 1,
        unit: "%",
      },
      {
        key: "automatically_hide_above",
        label: "Automatically Hide Above",
        description: "Similarity percentage above which artworks are automatically hidden from public view",
        type: "slider",
        defaultValue: 90,
        min: 0,
        max: 100,
        step: 1,
        unit: "%",
      },
      {
        key: "require_admin_approval",
        label: "Require Admin Approval",
        description: "Whether admin approval is required for all review decisions",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "auto_notify_artist",
        label: "Auto Notify Artist",
        description: "Whether artists are automatically notified about review results and decisions",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "auto_notify_admin",
        label: "Auto Notify Admin",
        description: "Whether admins are notified when new reviews are waiting in the queue",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "allow_false_positive_override",
        label: "Allow False Positive Override",
        description: "Whether admins can override similarity flags as false positives",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "maximum_review_days",
        label: "Maximum Review Days",
        description: "Maximum number of days an artwork can remain in review before automatic escalation",
        type: "number",
        defaultValue: 14,
        min: 1,
        max: 90,
        unit: "days",
      },
    ],
  },
  {
    id: "blockchain",
    label: "Blockchain",
    icon: "LinkIcon",
    description: "Blockchain registration and verification settings",
    settings: [
      {
        key: "default_chain",
        label: "Default Chain",
        description: "Default blockchain network for artwork registration",
        type: "select",
        defaultValue: "polygon-amoy",
        options: [
          { label: "Polygon Amoy (Testnet)", value: "polygon-amoy" },
          { label: "Polygon Mainnet", value: "polygon-mainnet" },
          { label: "Ethereum Sepolia (Testnet)", value: "ethereum-sepolia" },
          { label: "Ethereum Mainnet", value: "ethereum-mainnet" },
        ],
      },
      {
        key: "enable_blockchain_registration",
        label: "Enable Blockchain Registration",
        description: "Whether blockchain registration is enabled for new artwork submissions",
        type: "toggle",
        defaultValue: true,
        requiresConfirmation: true,
        confirmationMessage: "Disabling blockchain registration will stop new artwork registrations on-chain. Continue?",
      },
      {
        key: "retry_failed_transactions",
        label: "Retry Failed Transactions",
        description: "Whether to automatically retry failed blockchain transactions",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "maximum_retry_count",
        label: "Maximum Retry Count",
        description: "Maximum number of retries for failed blockchain transactions",
        type: "number",
        defaultValue: 3,
        min: 0,
        max: 10,
      },
      {
        key: "auto_register_after_upload",
        label: "Auto Register After Upload",
        description: "Whether artworks are automatically registered on the blockchain immediately after upload",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "display_blockchain_badge",
        label: "Display Blockchain Badge",
        description: "Whether to display blockchain verification badges on artwork detail pages",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "verification_timeout",
        label: "Verification Timeout",
        description: "Maximum time in seconds to wait for blockchain transaction verification",
        type: "number",
        defaultValue: 120,
        min: 30,
        max: 600,
        unit: "seconds",
      },
      {
        key: "explorer_base_url",
        label: "Explorer Base URL",
        description: "Base URL for the blockchain explorer used to generate transaction links",
        type: "text",
        defaultValue: "https://amoy.polygonscan.com",
        placeholder: "https://explorer.example.com",
      },
    ],
  },
  {
    id: "community",
    label: "Community",
    icon: "UsersIcon",
    description: "Community features and social interaction settings",
    settings: [
      {
        key: "enable_community_feed",
        label: "Enable Community Feed",
        description: "Whether the community feed feature is enabled for browsing all public artworks",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_upvotes",
        label: "Enable Upvotes",
        description: "Whether users can upvote artworks in the community feed",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_downvotes",
        label: "Enable Downvotes",
        description: "Whether users can downvote artworks in the community feed",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_comments",
        label: "Enable Comments",
        description: "Whether users can comment on artworks in the community feed",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_artwork_sharing",
        label: "Enable Artwork Sharing",
        description: "Whether users can share artworks to external platforms",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_artist_verification_badge",
        label: "Enable Artist Verification Badge",
        description: "Whether verified artist badges are displayed on artist profiles and artworks",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "allow_anonymous_viewing",
        label: "Allow Anonymous Viewing",
        description: "Whether unauthenticated users can view community content and artworks",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_nsfw_content",
        label: "Enable NSFW Content",
        description: "Whether NSFW content is allowed on the platform",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "minimum_reputation_required",
        label: "Minimum Reputation Required",
        description: "Minimum reputation score required to participate in community features like commenting",
        type: "number",
        defaultValue: 0,
        min: 0,
        max: 1000,
      },
    ],
  },
  {
    id: "reports",
    label: "Reports",
    icon: "FlagIcon",
    description: "Infringement reporting system configuration",
    settings: [
      {
        key: "enable_reporting",
        label: "Enable Reporting",
        description: "Whether the infringement reporting system is enabled",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "maximum_reports_per_day",
        label: "Maximum Reports Per Day",
        description: "Maximum number of reports a single user can submit per day",
        type: "number",
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        key: "auto_assign_reports",
        label: "Auto Assign Reports",
        description: "Whether reports are automatically assigned to available administrators",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "auto_escalate",
        label: "Auto Escalate",
        description: "Whether reports are automatically escalated after receiving multiple flags",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "escalation_threshold",
        label: "Escalation Threshold",
        description: "Number of reports on the same artwork before automatic escalation to senior admin",
        type: "number",
        defaultValue: 3,
        min: 2,
        max: 20,
      },
      {
        key: "default_report_status",
        label: "Default Report Status",
        description: "Default status for newly submitted reports",
        type: "select",
        defaultValue: "open",
        options: [
          { label: "Open", value: "open" },
          { label: "Under Review", value: "under_review" },
          { label: "Pending", value: "pending" },
        ],
      },
      {
        key: "maximum_evidence_files",
        label: "Maximum Evidence Files",
        description: "Maximum number of evidence files that can be attached to a single report",
        type: "number",
        defaultValue: 5,
        min: 1,
        max: 20,
      },
      {
        key: "maximum_evidence_size",
        label: "Maximum Evidence Size",
        description: "Maximum total size of evidence files per report in megabytes",
        type: "number",
        defaultValue: 20,
        min: 1,
        max: 200,
        unit: "MB",
      },
      {
        key: "require_explanation",
        label: "Require Explanation",
        description: "Whether reporters must provide a detailed explanation when submitting a report",
        type: "toggle",
        defaultValue: true,
      },
    ],
  },
  {
    id: "notifications",
    label: "Notifications",
    icon: "BellIcon",
    description: "Platform notification settings",
    settings: [
      {
        key: "enable_email_notifications",
        label: "Enable Email Notifications",
        description: "Whether email notifications are enabled for platform events",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "enable_in_app_notifications",
        label: "Enable In-App Notifications",
        description: "Whether in-app notification badges and alerts are enabled",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "notify_on_reports",
        label: "Notify on Reports",
        description: "Whether to send notifications when new reports are submitted",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "notify_on_blockchain_success",
        label: "Notify on Blockchain Success",
        description: "Whether to notify users when blockchain registration succeeds",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "notify_on_similarity_detection",
        label: "Notify on Similarity Detection",
        description: "Whether to notify users when similar artworks are detected",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "notify_on_manual_review",
        label: "Notify on Manual Review",
        description: "Whether to notify users when their artwork enters manual review",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "notify_on_report_resolution",
        label: "Notify on Report Resolution",
        description: "Whether to notify users when a report they filed is resolved",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "notification_retention_days",
        label: "Notification Retention",
        description: "Number of days to retain notifications before automatic cleanup",
        type: "number",
        defaultValue: 90,
        min: 7,
        max: 365,
        unit: "days",
      },
    ],
  },
  {
    id: "security",
    label: "Security",
    icon: "LockIcon",
    description: "Platform security and access control settings",
    settings: [
      {
        key: "maximum_login_attempts",
        label: "Maximum Login Attempts",
        description: "Maximum failed login attempts before account lockout",
        type: "number",
        defaultValue: 5,
        min: 1,
        max: 20,
      },
      {
        key: "session_timeout",
        label: "Session Timeout",
        description: "User session timeout in seconds before automatic logout",
        type: "number",
        defaultValue: 3600,
        min: 300,
        max: 86400,
        unit: "seconds",
      },
      {
        key: "password_reset_expiration",
        label: "Password Reset Expiration",
        description: "Password reset link expiration time in seconds",
        type: "number",
        defaultValue: 3600,
        min: 300,
        max: 86400,
        unit: "seconds",
      },
      {
        key: "require_verified_email",
        label: "Require Verified Email",
        description: "Whether users must verify their email address before accessing the platform",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "allowed_origins",
        label: "Allowed Origins",
        description: "List of allowed CORS origins for API access (one per line)",
        type: "tags",
        defaultValue: [],
        badge: "advanced",
      },
      {
        key: "enable_audit_logs",
        label: "Enable Audit Logs",
        description: "Whether administrative audit logging is enabled for tracking all admin actions",
        type: "toggle",
        defaultValue: true,
        badge: "recommended",
      },
      {
        key: "admin_session_timeout",
        label: "Admin Session Timeout",
        description: "Admin session timeout in seconds for enhanced security",
        type: "number",
        defaultValue: 1800,
        min: 300,
        max: 43200,
        unit: "seconds",
        badge: "recommended",
      },
    ],
  },
  {
    id: "storage",
    label: "Storage",
    icon: "HardDriveIcon",
    description: "Cloud storage usage and metrics (read-only)",
    settings: [
      {
        key: "storage_cloudinary_usage",
        label: "Cloudinary Usage",
        description: "Current Cloudinary media storage usage",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "storage_used",
        label: "Storage Used",
        description: "Total storage space currently used",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "remaining_storage",
        label: "Remaining Storage",
        description: "Available storage space remaining",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "average_artwork_size",
        label: "Average Artwork Size",
        description: "Average file size per registered artwork",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "total_registered_files",
        label: "Total Registered Files",
        description: "Total number of registered artwork files",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "database_size",
        label: "Database Size",
        description: "Current database size (if available)",
        type: "readonly",
        defaultValue: "Loading...",
      },
    ],
  },
  {
    id: "maintenance",
    label: "Maintenance",
    icon: "WrenchIcon",
    description: "Platform maintenance mode and scheduled downtime settings",
    settings: [
      {
        key: "maintenance_mode",
        label: "Maintenance Mode",
        description: "When enabled, the platform will display a maintenance message to all non-admin users",
        type: "toggle",
        defaultValue: false,
        requiresConfirmation: true,
        confirmationMessage: "Enabling maintenance mode will prevent all users from accessing the platform. Only admins will be able to log in. Continue?",
      },
      {
        key: "maintenance_message",
        label: "Maintenance Message",
        description: "Message displayed to users when maintenance mode is active",
        type: "textarea",
        defaultValue: "We are currently performing scheduled maintenance. Please check back shortly.",
        placeholder: "Enter maintenance message...",
      },
      {
        key: "scheduled_maintenance",
        label: "Scheduled Maintenance",
        description: "Whether scheduled maintenance is planned",
        type: "toggle",
        defaultValue: false,
      },
      {
        key: "allow_admin_login_during_maintenance",
        label: "Allow Admin Login During Maintenance",
        description: "Whether administrators can log in to the platform during maintenance mode",
        type: "toggle",
        defaultValue: true,
      },
      {
        key: "display_countdown",
        label: "Display Countdown",
        description: "Whether to display a countdown timer to users for scheduled maintenance",
        type: "toggle",
        defaultValue: false,
      },
    ],
  },
  {
    id: "system-info",
    label: "System Information",
    icon: "InfoIcon",
    description: "Read-only system information and version details",
    settings: [
      {
        key: "nextjs_version",
        label: "Next.js Version",
        description: "Current Next.js framework version",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "react_version",
        label: "React Version",
        description: "Current React library version",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "supabase_project",
        label: "Supabase Project",
        description: "Connected Supabase project reference",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "database_version",
        label: "Database Version",
        description: "PostgreSQL database version",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "blockchain_network",
        label: "Blockchain Network",
        description: "Connected blockchain network name",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "environment",
        label: "Environment",
        description: "Current application environment",
        type: "readonly",
        defaultValue: "Loading...",
      },
      {
        key: "build_date",
        label: "Build Date",
        description: "Date and time of the last application build",
        type: "readonly",
        defaultValue: "Loading...",
      },
    ],
  },
];

// ============================================
// Helper: Get category by ID
// ============================================

export function getCategoryById(id: string): SettingsCategory | undefined {
  return SETTINGS_CATEGORIES.find((cat) => cat.id === id);
}

// ============================================
// Helper: Get setting definition by key
// ============================================

export function getSettingByKey(key: string): SettingDefinition | undefined {
  for (const category of SETTINGS_CATEGORIES) {
    const setting = category.settings.find((s) => s.key === key);
    if (setting) return setting;
  }
  return undefined;
}

// ============================================
// Category IDs that require confirmation on reset
// ============================================

export const CATEGORIES_REQUIRING_CONFIRMATION: string[] = [
  "similarity",
  "blockchain",
  "maintenance",
  "security",
];

// ============================================
// Critical setting keys that require confirmation
// ============================================

export const CRITICAL_SETTING_KEYS: string[] = [
  "similarity_threshold",
  "automatic_approval_threshold",
  "maintenance_mode",
  "enable_blockchain_registration",
  "default_chain",
];