-- ART GENRES

create table public.art_genres (
  art_id uuid not null,
  genre_id smallint not null,
  id smallint generated by default as identity not null,
  constraint art_genres_pkey primary key (id),
  constraint art_genres_art_id_fkey foreign KEY (art_id) references registered_arts (id) on delete CASCADE,
  constraint art_genres_genre_id_fkey foreign KEY (genre_id) references genres (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_art_genres_genre_id on public.art_genres using btree (genre_id) TABLESPACE pg_default;

create index IF not exists idx_art_genres_art_id on public.art_genres using btree (art_id) TABLESPACE pg_default;


-- ART POSTS

create table public.art_posts (
  id uuid not null default gen_random_uuid (),
  art_id uuid not null,
  user_id uuid not null,
  visibility public.art_post_visibility not null default 'public'::art_post_visibility,
  is_archived boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  upvote_count integer not null default 0,
  downvote_count integer not null default 0,
  score integer not null default 0,
  is_nsfw boolean null default false,
  constraint art_posts_pkey primary key (id),
  constraint art_posts_art_id_fkey foreign KEY (art_id) references registered_arts (id) on update CASCADE on delete CASCADE,
  constraint art_posts_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE,
  constraint art_posts_downvote_count_check check ((downvote_count >= 0)),
  constraint art_posts_upvote_count_check check ((upvote_count >= 0))
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_art_posts_art_id on public.art_posts using btree (art_id) TABLESPACE pg_default;

create index IF not exists idx_art_posts_user_id on public.art_posts using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_art_posts_art_id on public.art_posts using btree (art_id) TABLESPACE pg_default;

create index IF not exists idx_art_posts_visibility on public.art_posts using btree (visibility) TABLESPACE pg_default;

create index IF not exists idx_art_posts_created_at on public.art_posts using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_art_posts_public_feed on public.art_posts using btree (created_at desc) TABLESPACE pg_default
where
  (
    (visibility = 'public'::art_post_visibility)
    and (is_archived = false)
  );

create index IF not exists idx_art_posts_user_visibility_created on public.art_posts using btree (user_id, visibility, created_at desc) TABLESPACE pg_default;

create index IF not exists art_posts_is_nsfw_idx on public.art_posts using btree (is_nsfw) TABLESPACE pg_default;

create trigger trg_art_posts_updated_at BEFORE
update on art_posts for EACH row
execute FUNCTION set_updated_at ();

create trigger trg_enforce_art_post_owner_match BEFORE INSERT
or
update on art_posts for EACH row
execute FUNCTION enforce_art_post_owner_match ();



-- ART REACTIONS

create table public.art_reactions (
  id uuid not null default gen_random_uuid (),
  post_id uuid not null,
  user_id uuid not null,
  reaction_type public.art_reaction_type not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint art_reactions_pkey primary key (id),
  constraint art_reactions_post_id_fkey foreign KEY (post_id) references art_posts (id) on delete CASCADE,
  constraint art_reactions_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_art_reactions_post_user on public.art_reactions using btree (post_id, user_id) TABLESPACE pg_default;

create index IF not exists idx_art_reactions_post_id on public.art_reactions using btree (post_id) TABLESPACE pg_default;

create index IF not exists idx_art_reactions_user_id on public.art_reactions using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_art_reactions_type on public.art_reactions using btree (reaction_type) TABLESPACE pg_default;

create trigger trg_art_reactions_sync_counts_delete
after DELETE on art_reactions for EACH row
execute FUNCTION sync_art_post_vote_counts_incremental ();

create trigger trg_art_reactions_sync_counts_insert
after INSERT on art_reactions for EACH row
execute FUNCTION sync_art_post_vote_counts_incremental ();

create trigger trg_art_reactions_sync_counts_update
after
update on art_reactions for EACH row
execute FUNCTION sync_art_post_vote_counts_incremental ();

create trigger trg_art_reactions_updated_at BEFORE
update on art_reactions for EACH row
execute FUNCTION set_updated_at ();


-- ART SIMILARITY SCANS

create table public.art_similarity_scans (
  id uuid not null default gen_random_uuid (),
  art_id uuid not null,
  owner_id uuid not null,
  status text not null default 'pending'::text,
  filename text null,
  original_hash text null,
  success boolean not null default false,
  total_matches integer not null default 0,
  best_source text null,
  best_link text null,
  best_url text null,
  best_match_pair text null,
  best_similarity_percentage numeric(5, 2) null,
  best_min_combined_distance numeric(10, 4) null,
  best_average_combined_distance numeric(10, 4) null,
  best_max_combined_distance numeric(10, 4) null,
  matches jsonb not null default '[]'::jsonb,
  hashes jsonb null,
  raw_response jsonb null,
  error_message text null,
  started_at timestamp with time zone null,
  completed_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint art_similarity_scans_pkey primary key (id),
  constraint uq_art_similarity_scans_art_id unique (art_id),
  constraint art_similarity_scans_art_id_fkey foreign KEY (art_id) references registered_arts (id) on delete CASCADE,
  constraint art_similarity_scans_owner_id_fkey foreign KEY (owner_id) references users (id) on delete CASCADE,
  constraint art_similarity_scans_best_similarity_percentage_check check (
    (
      (best_similarity_percentage is null)
      or (
        (best_similarity_percentage >= (0)::numeric)
        and (best_similarity_percentage <= (100)::numeric)
      )
    )
  ),
  constraint art_similarity_scans_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'running'::text,
          'completed'::text,
          'failed'::text,
          'cancelled'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_owner_id on public.art_similarity_scans using btree (owner_id) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_status on public.art_similarity_scans using btree (status) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_success on public.art_similarity_scans using btree (success) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_best_similarity on public.art_similarity_scans using btree (best_similarity_percentage desc) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_best_source on public.art_similarity_scans using btree (best_source) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_created_at on public.art_similarity_scans using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_matches_gin on public.art_similarity_scans using gin (matches jsonb_path_ops) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_raw_response_gin on public.art_similarity_scans using gin (raw_response jsonb_path_ops) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_hashes_gin on public.art_similarity_scans using gin (hashes jsonb_path_ops) TABLESPACE pg_default;

create trigger trg_art_similarity_scans_updated_at BEFORE
update on art_similarity_scans for EACH row
execute FUNCTION set_updated_at ();

create trigger trg_notify_art_similarity_scan_status
after
update on art_similarity_scans for EACH row
execute FUNCTION notify_art_similarity_scan_status ();


-- GENRES

create table public.genres (
  id smallint generated always as identity not null,
  name text not null,
  constraint genres_pkey primary key (id),
  constraint genres_name_key unique (name)
) TABLESPACE pg_default;



-- NOTIFICATIONS

create table public.notifications (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  type text not null,
  title text not null,
  message text not null,
  related_art_id uuid null,
  related_report_id uuid null,
  related_scan_id uuid null,
  action_url text null,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  read_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint notifications_pkey primary key (id),
  constraint notifications_related_art_id_fkey foreign KEY (related_art_id) references registered_arts (id) on delete CASCADE,
  constraint notifications_related_report_id_fkey foreign KEY (related_report_id) references reports (id) on delete CASCADE,
  constraint notifications_related_scan_id_fkey foreign KEY (related_scan_id) references art_similarity_scans (id) on delete CASCADE,
  constraint notifications_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE,
  constraint notifications_type_check check (
    (
      type = any (
        array[
          'artwork_registered'::text,
          'scan_completed'::text,
          'scan_flagged'::text,
          'scan_failed'::text,
          'report_submitted'::text,
          'report_resolved'::text,
          'blockchain_recorded'::text,
          'system_announcement'::text,
          'artwork_verified'::text,
          'artwork_verification_rejected'::text,
          'artwork_verification_info_requested'::text,
          'artwork_verification_resubmitted'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_notifications_report_event on public.notifications using btree (user_id, related_report_id, type) TABLESPACE pg_default
where
  (related_report_id is not null);

create unique INDEX IF not exists uq_notifications_scan_event on public.notifications using btree (user_id, related_scan_id, type) TABLESPACE pg_default
where
  (related_scan_id is not null);

create index IF not exists idx_notifications_user_id on public.notifications using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_notifications_user_created_at on public.notifications using btree (user_id, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_notifications_user_is_read on public.notifications using btree (user_id, is_read) TABLESPACE pg_default;

create index IF not exists idx_notifications_user_unread_created_at on public.notifications using btree (user_id, is_read, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_notifications_type on public.notifications using btree (type) TABLESPACE pg_default;

create index IF not exists idx_notifications_related_art_id on public.notifications using btree (related_art_id) TABLESPACE pg_default;

create index IF not exists idx_notifications_related_report_id on public.notifications using btree (related_report_id) TABLESPACE pg_default;

create index IF not exists idx_notifications_related_scan_id on public.notifications using btree (related_scan_id) TABLESPACE pg_default;

create unique INDEX IF not exists uq_notifications_blockchain_event on public.notifications using btree (user_id, related_art_id, type) TABLESPACE pg_default
where
  (
    (type = 'blockchain_recorded'::text)
    and (related_art_id is not null)
  );



-- REGISTERED ARTS

create table public.registered_arts (
  id uuid not null default gen_random_uuid (),
  owner_id uuid not null,
  title text not null,
  description text null,
  c_asset_id text null,
  c_secure_url text null,
  file_hash text not null,
  perceptual_hash text not null,
  author_id_hash text null,
  evidence_hash text null,
  evidence jsonb null,
  chain text null,
  tx_hash text null,
  block_number bigint null,
  work_id text null,
  status public.art_status not null default 'pending_blockchain'::art_status,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  plagiarism_hashes json null,
  constraint registered_arts_pkey primary key (id),
  constraint registered_arts_tx_hash_key unique (tx_hash),
  constraint registered_arts_owner_id_fkey foreign KEY (owner_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_owner on public.registered_arts using btree (owner_id) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_status on public.registered_arts using btree (status) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_created_at on public.registered_arts using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_file_hash on public.registered_arts using btree (file_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_phash on public.registered_arts using btree (perceptual_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_work_id on public.registered_arts using btree (work_id) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_author_id_hash on public.registered_arts using btree (author_id_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_evidence_hash on public.registered_arts using btree (evidence_hash) TABLESPACE pg_default;

create unique INDEX IF not exists uq_registered_arts_owner_file on public.registered_arts using btree (owner_id, file_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_tx_hash on public.registered_arts using btree (tx_hash) TABLESPACE pg_default;

create trigger trg_notify_artwork_registered
after INSERT on registered_arts for EACH row
execute FUNCTION notify_artwork_registered ();

create trigger trg_notify_blockchain_recorded
after
update on registered_arts for EACH row
execute FUNCTION notify_blockchain_recorded ();

create trigger trg_registered_arts_updated_at BEFORE
update on registered_arts for EACH row
execute FUNCTION set_updated_at ();



-- REPORTS

create table public.reports (
  id uuid not null default gen_random_uuid (),
  reporter_id uuid not null,
  reported_art_post_id uuid not null,
  report_type public.report_type not null,
  title text not null,
  description text not null,
  status public.report_status not null default 'open'::report_status,
  created_at timestamp with time zone not null default now(),
  resolved_at timestamp with time zone null,
  constraint reports_pkey primary key (id),
  constraint reports_reported_art_post_id_fkey foreign KEY (reported_art_post_id) references art_posts (id),
  constraint reports_reporter_id_fkey foreign KEY (reporter_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_reports_status on public.reports using btree (status) TABLESPACE pg_default;

create index IF not exists idx_reports_reported_art_id on public.reports using btree (reported_art_post_id) TABLESPACE pg_default;

create index IF not exists idx_reports_reporter_id on public.reports using btree (reporter_id) TABLESPACE pg_default;

create index IF not exists idx_reports_created_at on public.reports using btree (created_at desc) TABLESPACE pg_default;

create trigger trg_notify_report_resolved
after
update on reports for EACH row
execute FUNCTION notify_report_resolved ();

create trigger trg_notify_report_submitted_to_admins
after INSERT on reports for EACH row
execute FUNCTION notify_report_submitted_to_admins ();

create trigger trg_notify_report_submitted_to_reporter
after INSERT on reports for EACH row
execute FUNCTION notify_report_submitted_to_reporter ();



-- USERS

-- Account status enum for user management
create type public.account_status as enum ('active', 'suspended', 'banned');

create table public.users (
  id uuid not null,
  first_name text not null,
  last_name text not null,
  middle_name text null,
  username public.citext not null,
  bio text null,
  c_profile_image text null,
  is_verified boolean not null default false,
  role public.user_role not null default 'user'::user_role,
  account_status public.account_status not null default 'active'::account_status,
  suspended_until timestamp with time zone null,
  suspension_reason text null,
  country text null,
  last_active timestamp with time zone not null default now(),
  is_online boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  email text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_username_key unique (username),
  constraint users_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint username_len check (
    (
      (char_length((username)::text) >= 3)
      and (char_length((username)::text) <= 30)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_users_username on public.users using btree (username) TABLESPACE pg_default;

create index IF not exists idx_users_role on public.users using btree (role) TABLESPACE pg_default;

create index IF not exists idx_users_account_status on public.users using btree (account_status) TABLESPACE pg_default;

create index IF not exists idx_users_last_active on public.users using btree (last_active desc) TABLESPACE pg_default;

create trigger trg_initialize_user_preferences
after INSERT on users for EACH row
execute FUNCTION handle_new_user_preferences ();

create trigger trg_users_updated_at BEFORE
update on users for EACH row
execute FUNCTION set_updated_at ();



-- USER PREFERENCES

create table public.user_preferences (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  show_nsfw_content boolean null default false,
  constraint user_preferences_pkey primary key (id),
  constraint user_preferences_user_id_key unique (user_id),
  constraint user_preferences_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_user_preferences_user_id on public.user_preferences using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_user_preferences_nsfw_false on public.user_preferences using btree (user_id) TABLESPACE pg_default
where
  (show_nsfw_content = false);

create index IF not exists user_preferences_show_nsfw_content_idx on public.user_preferences using btree (show_nsfw_content) TABLESPACE pg_default;

create trigger tr_update_user_preferences_timestamp BEFORE
update on user_preferences for EACH row
execute FUNCTION update_user_preferences_timestamp ();



-- REPORT COMMENTS

create table public.report_comments (
  id uuid not null default gen_random_uuid(),
  report_id uuid not null,
  user_id uuid not null,
  message text not null,
  is_admin boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint report_comments_pkey primary key (id),
  constraint report_comments_report_id_fkey foreign key (report_id) references reports (id) on delete cascade,
  constraint report_comments_user_id_fkey foreign key (user_id) references users (id) on delete cascade
) TABLESPACE pg_default;

create index IF not exists idx_report_comments_report_id on public.report_comments using btree (report_id) TABLESPACE pg_default;
create index IF not exists idx_report_comments_created_at on public.report_comments using btree (report_id, created_at desc) TABLESPACE pg_default;
create index IF not exists idx_report_comments_user_id on public.report_comments using btree (user_id) TABLESPACE pg_default;



-- REPORT EVIDENCE

create table public.report_evidence (
  id uuid not null default gen_random_uuid(),
  report_id uuid not null,
  uploaded_by uuid not null,
  file_url text not null,
  file_name text not null,
  mime_type text null,
  description text null,
  created_at timestamp with time zone not null default now(),
  constraint report_evidence_pkey primary key (id),
  constraint report_evidence_report_id_fkey foreign key (report_id) references reports (id) on delete cascade,
  constraint report_evidence_uploaded_by_fkey foreign key (uploaded_by) references users (id) on delete cascade
) TABLESPACE pg_default;

create index IF not exists idx_report_evidence_report_id on public.report_evidence using btree (report_id) TABLESPACE pg_default;
create index IF not exists idx_report_evidence_uploaded_by on public.report_evidence using btree (uploaded_by) TABLESPACE pg_default;



-- REPORT ACTIONS (Audit Trail)

create table public.report_actions (
  id uuid not null default gen_random_uuid(),
  report_id uuid not null,
  admin_id uuid not null,
  action text not null,
  previous_status public.report_status null,
  new_status public.report_status null,
  notes text null,
  created_at timestamp with time zone not null default now(),
  constraint report_actions_pkey primary key (id),
  constraint report_actions_report_id_fkey foreign key (report_id) references reports (id) on delete cascade,
  constraint report_actions_admin_id_fkey foreign key (admin_id) references users (id) on delete cascade,
  constraint report_actions_action_check check (
    action = any (array[
      'status_change'::text,
      'evidence_requested'::text,
      'evidence_uploaded'::text,
      'comment_added'::text,
      'decision_recorded'::text,
      'report_created'::text
    ])
  )
) TABLESPACE pg_default;

create index IF not exists idx_report_actions_report_id on public.report_actions using btree (report_id) TABLESPACE pg_default;
create index IF not exists idx_report_actions_admin_id on public.report_actions using btree (admin_id) TABLESPACE pg_default;
create index IF not exists idx_report_actions_created_at on public.report_actions using btree (report_id, created_at desc) TABLESPACE pg_default;



-- REPORT DECISIONS

create table public.report_decisions (
  id uuid not null default gen_random_uuid(),
  report_id uuid not null,
  admin_id uuid not null,
  decision text not null,
  summary text not null,
  created_at timestamp with time zone not null default now(),
  constraint report_decisions_pkey primary key (id),
  constraint report_decisions_report_id_key unique (report_id),
  constraint report_decisions_report_id_fkey foreign key (report_id) references reports (id) on delete cascade,
  constraint report_decisions_admin_id_fkey foreign key (admin_id) references users (id) on delete cascade,
  constraint report_decisions_decision_check check (
    decision = any (array[
      'infringement_confirmed'::text,
      'no_violation'::text,
      'insufficient_evidence'::text,
      'duplicate_report'::text,
      'other'::text
    ])
  )
) TABLESPACE pg_default;

create index IF not exists idx_report_decisions_report_id on public.report_decisions using btree (report_id) TABLESPACE pg_default;
create index IF not exists idx_report_decisions_admin_id on public.report_decisions using btree (admin_id) TABLESPACE pg_default;



-- Additional indexes for reports performance

create index IF not exists idx_reports_status_created on public.reports using btree (status, created_at desc) TABLESPACE pg_default;
create index IF not exists idx_reports_reporter_status on public.reports using btree (reporter_id, status) TABLESPACE pg_default;
create index IF not exists idx_reports_report_type on public.reports using btree (report_type) TABLESPACE pg_default;



-- ADMIN AUDIT LOGS
-- Tracks all administrative actions for accountability and audit trail

create table public.admin_audit_logs (
  id uuid not null default gen_random_uuid(),
  admin_id uuid not null,
  target_user_id uuid null,
  action text not null,
  reason text null,
  previous_value text null,
  new_value text null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text null,
  created_at timestamp with time zone not null default now(),
  constraint admin_audit_logs_pkey primary key (id),
  constraint admin_audit_logs_admin_id_fkey foreign key (admin_id) references users (id) on delete cascade,
  constraint admin_audit_logs_target_user_id_fkey foreign key (target_user_id) references users (id) on delete set null,
  constraint admin_audit_logs_action_check check (
    action = any (array[
      'suspend_user'::text,
      'ban_user'::text,
      'reactivate_user'::text,
      'verify_artist'::text,
      'remove_verification'::text,
      'reset_password'::text,
      'send_notification'::text,
      'force_logout'::text,
      'delete_account'::text,
      'bulk_suspend'::text,
      'bulk_ban'::text,
      'bulk_verify'::text,
      'export_users'::text
    ])
  )
) TABLESPACE pg_default;

create index IF not exists idx_admin_audit_logs_admin_id on public.admin_audit_logs using btree (admin_id) TABLESPACE pg_default;
create index IF not exists idx_admin_audit_logs_target_user_id on public.admin_audit_logs using btree (target_user_id) TABLESPACE pg_default;
create index IF not exists idx_admin_audit_logs_action on public.admin_audit_logs using btree (action) TABLESPACE pg_default;
create index IF not exists idx_admin_audit_logs_created_at on public.admin_audit_logs using btree (created_at desc) TABLESPACE pg_default;



-- ARTWORK REVIEWS
-- Tracks manual review queue for artworks flagged by plagiarism detection

create table public.artwork_reviews (
  id uuid not null default gen_random_uuid(),
  artwork_id uuid not null,
  reviewer_id uuid null,
  status text not null default 'pending'::text,
  decision text null,
  decision_reason text null,
  review_notes text null,
  requested_documents jsonb not null default '[]'::jsonb,
  assigned_at timestamp with time zone null,
  reviewed_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint artwork_reviews_pkey primary key (id),
  constraint artwork_reviews_artwork_id_key unique (artwork_id),
  constraint artwork_reviews_artwork_id_fkey foreign key (artwork_id) references registered_arts (id) on delete cascade,
  constraint artwork_reviews_reviewer_id_fkey foreign key (reviewer_id) references users (id) on delete set null,
  constraint artwork_reviews_status_check check (
    status = any (array['pending'::text, 'under_review'::text, 'needs_info'::text, 'approved'::text, 'rejected'::text])
  ),
  constraint artwork_reviews_decision_check check (
    decision is null or decision = any (array['approved'::text, 'rejected'::text, 'needs_info'::text])
  )
) TABLESPACE pg_default;

create index IF not exists idx_artwork_reviews_status on public.artwork_reviews using btree (status) TABLESPACE pg_default;
create index IF not exists idx_artwork_reviews_reviewer_id on public.artwork_reviews using btree (reviewer_id) TABLESPACE pg_default;
create index IF not exists idx_artwork_reviews_created_at on public.artwork_reviews using btree (created_at desc) TABLESPACE pg_default;
create index IF not exists idx_artwork_reviews_artwork_id on public.artwork_reviews using btree (artwork_id) TABLESPACE pg_default;

create trigger trg_artwork_reviews_updated_at before
update on artwork_reviews for each row
execute function set_updated_at ();



-- ARTWORK REVIEW ACTIONS (Audit Trail)

create table public.artwork_review_actions (
  id uuid not null default gen_random_uuid(),
  review_id uuid not null,
  admin_id uuid not null,
  action text not null,
  previous_status text null,
  new_status text null,
  notes text null,
  created_at timestamp with time zone not null default now(),
  constraint artwork_review_actions_pkey primary key (id),
  constraint artwork_review_actions_review_id_fkey foreign key (review_id) references artwork_reviews (id) on delete cascade,
  constraint artwork_review_actions_admin_id_fkey foreign key (admin_id) references users (id) on delete cascade,
  constraint artwork_review_actions_action_check check (
    action = any (array[
      'viewed'::text,
      'assigned'::text,
      'unassigned'::text,
      'approved'::text,
      'rejected'::text,
      'comment_added'::text,
      'information_requested'::text,
      'decision_changed'::text,
      'blockchain_triggered'::text
    ])
  )
) TABLESPACE pg_default;

create index IF not exists idx_artwork_review_actions_review_id on public.artwork_review_actions using btree (review_id) TABLESPACE pg_default;
create index IF not exists idx_artwork_review_actions_admin_id on public.artwork_review_actions using btree (admin_id) TABLESPACE pg_default;
create index IF not exists idx_artwork_review_actions_created_at on public.artwork_review_actions using btree (review_id, created_at desc) TABLESPACE pg_default;



-- SYSTEM SETTINGS
-- Stores all configurable platform settings as key-value pairs
-- with JSONB values for flexible data types

create table public.system_settings (
  id uuid not null default gen_random_uuid(),
  key text not null,
  value jsonb not null default '{}'::jsonb,
  description text null,
  updated_by uuid null,
  updated_at timestamp with time zone not null default now(),
  constraint system_settings_pkey primary key (id),
  constraint system_settings_key_key unique (key),
  constraint system_settings_updated_by_fkey foreign key (updated_by) references users (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_system_settings_key on public.system_settings using btree (key) TABLESPACE pg_default;
create index IF not exists idx_system_settings_updated_by on public.system_settings using btree (updated_by) TABLESPACE pg_default;
create index IF not exists idx_system_settings_updated_at on public.system_settings using btree (updated_at desc) TABLESPACE pg_default;

create trigger trg_system_settings_updated_at BEFORE
update on system_settings for EACH row
execute FUNCTION set_updated_at ();

-- Enable RLS and create policies for system_settings
alter table public.system_settings enable row level security;

create policy "Admins can read system_settings"
  on public.system_settings for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

create policy "Admins can insert system_settings"
  on public.system_settings for insert
  with check (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

create policy "Admins can update system_settings"
  on public.system_settings for update
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

create policy "Admins can delete system_settings"
  on public.system_settings for delete
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );



-- SETTINGS AUDIT LOGS
-- Tracks all configuration changes for accountability

create table public.settings_audit_logs (
  id uuid not null default gen_random_uuid(),
  admin_id uuid not null,
  setting_key text not null,
  previous_value jsonb null,
  new_value jsonb null,
  reason text null,
  created_at timestamp with time zone not null default now(),
  constraint settings_audit_logs_pkey primary key (id),
  constraint settings_audit_logs_admin_id_fkey foreign key (admin_id) references users (id) on delete cascade
) TABLESPACE pg_default;

create index IF not exists idx_settings_audit_logs_admin_id on public.settings_audit_logs using btree (admin_id) TABLESPACE pg_default;
create index IF not exists idx_settings_audit_logs_setting_key on public.settings_audit_logs using btree (setting_key) TABLESPACE pg_default;
create index IF not exists idx_settings_audit_logs_created_at on public.settings_audit_logs using btree (created_at desc) TABLESPACE pg_default;

-- Enable RLS and create policies for settings_audit_logs
alter table public.settings_audit_logs enable row level security;

create policy "Admins can read settings_audit_logs"
  on public.settings_audit_logs for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

create policy "Admins can insert settings_audit_logs"
  on public.settings_audit_logs for insert
  with check (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- ============================================
-- ROW LEVEL SECURITY: Reports & Related Tables
-- ============================================

-- Enable RLS on reports and related tables
alter table public.reports enable row level security;
alter table public.report_comments enable row level security;
alter table public.report_evidence enable row level security;
alter table public.report_actions enable row level security;
alter table public.report_decisions enable row level security;

-- Reports: Allow reporters to read their own reports
create policy "Reporters can read own reports"
  on public.reports for select
  using (reporter_id = auth.uid());

-- Reports: Allow admins to read all reports
create policy "Admins can read all reports"
  on public.reports for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Reports: Allow authenticated users to create reports
create policy "Authenticated users can create reports"
  on public.reports for insert
  with check (reporter_id = auth.uid());

-- Reports: Allow admins to update reports
create policy "Admins can update reports"
  on public.reports for update
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Reports: Allow admins to delete reports
create policy "Admins can delete reports"
  on public.reports for delete
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Comments: Allow reporters to read comments on own reports
create policy "Reporters can read comments on own reports"
  on public.report_comments for select
  using (
    exists (
      select 1 from public.reports
      where reports.id = report_comments.report_id
      and reports.reporter_id = auth.uid()
    )
  );

-- Report Comments: Allow admins to read all comments
create policy "Admins can read all report comments"
  on public.report_comments for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Comments: Allow authenticated users to comment on own reports
create policy "Authenticated users can create comments on own reports"
  on public.report_comments for insert
  with check (
    user_id = auth.uid()
    and (
      exists (
        select 1 from public.reports
        where reports.id = report_comments.report_id
        and reports.reporter_id = auth.uid()
      )
    )
  );

-- Report Comments: Allow admins to comment on any report
create policy "Admins can create comments on any report"
  on public.report_comments for insert
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Evidence: Allow reporters to read evidence on own reports
create policy "Reporters can read evidence on own reports"
  on public.report_evidence for select
  using (
    exists (
      select 1 from public.reports
      where reports.id = report_evidence.report_id
      and reports.reporter_id = auth.uid()
    )
  );

-- Report Evidence: Allow admins to read all evidence
create policy "Admins can read all report evidence"
  on public.report_evidence for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Evidence: Allow authenticated users to upload evidence to own reports
create policy "Authenticated users can upload evidence to own reports"
  on public.report_evidence for insert
  with check (
    uploaded_by = auth.uid()
    and (
      exists (
        select 1 from public.reports
        where reports.id = report_evidence.report_id
        and reports.reporter_id = auth.uid()
      )
    )
  );

-- Report Evidence: Allow admins to upload evidence to any report
create policy "Admins can upload evidence to any report"
  on public.report_evidence for insert
  with check (
    uploaded_by = auth.uid()
    and exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Actions: Allow reporters to read actions on own reports
create policy "Reporters can read actions on own reports"
  on public.report_actions for select
  using (
    exists (
      select 1 from public.reports
      where reports.id = report_actions.report_id
      and reports.reporter_id = auth.uid()
    )
  );

-- Report Actions: Allow admins to read all actions
create policy "Admins can read all report actions"
  on public.report_actions for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Actions: Allow admins to insert actions
create policy "Admins can insert report actions"
  on public.report_actions for insert
  with check (
    admin_id = auth.uid()
    and exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Decisions: Allow reporters to read decisions on own reports
create policy "Reporters can read decisions on own reports"
  on public.report_decisions for select
  using (
    exists (
      select 1 from public.reports
      where reports.id = report_decisions.report_id
      and reports.reporter_id = auth.uid()
    )
  );

-- Report Decisions: Allow admins to read all decisions
create policy "Admins can read all report decisions"
  on public.report_decisions for select
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );

-- Report Decisions: Allow admins to insert decisions
create policy "Admins can insert report decisions"
  on public.report_decisions for insert
  with check (
    admin_id = auth.uid()
    and exists (
      select 1 from public.users
      where users.id = auth.uid()
      and users.role = 'admin'
    )
  );
