-- ART GENRES

create table public.art_genres (
  art_id uuid not null,
  genre_id smallint not null,
  id smallint generated by default as identity not null,
  constraint art_genres_pkey primary key (id),
  constraint art_genres_art_id_fkey foreign KEY (art_id) references registered_arts (id) on delete CASCADE,
  constraint art_genres_genre_id_fkey foreign KEY (genre_id) references genres (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_art_genres_genre_id on public.art_genres using btree (genre_id) TABLESPACE pg_default;

create index IF not exists idx_art_genres_art_id on public.art_genres using btree (art_id) TABLESPACE pg_default;


-- ART POSTS

create table public.art_posts (
  id uuid not null default gen_random_uuid (),
  art_id uuid not null,
  user_id uuid not null,
  visibility public.art_post_visibility not null default 'public'::art_post_visibility,
  is_archived boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  upvote_count integer not null default 0,
  downvote_count integer not null default 0,
  score integer not null default 0,
  constraint art_posts_pkey primary key (id),
  constraint art_posts_art_id_fkey foreign KEY (art_id) references registered_arts (id) on update CASCADE on delete CASCADE,
  constraint art_posts_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE,
  constraint art_posts_downvote_count_check check ((downvote_count >= 0)),
  constraint art_posts_upvote_count_check check ((upvote_count >= 0))
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_art_posts_art_id on public.art_posts using btree (art_id) TABLESPACE pg_default;

create index IF not exists idx_art_posts_user_id on public.art_posts using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_art_posts_art_id on public.art_posts using btree (art_id) TABLESPACE pg_default;

create index IF not exists idx_art_posts_visibility on public.art_posts using btree (visibility) TABLESPACE pg_default;

create index IF not exists idx_art_posts_created_at on public.art_posts using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_art_posts_public_feed on public.art_posts using btree (created_at desc) TABLESPACE pg_default
where
  (
    (visibility = 'public'::art_post_visibility)
    and (is_archived = false)
  );

create index IF not exists idx_art_posts_user_visibility_created on public.art_posts using btree (user_id, visibility, created_at desc) TABLESPACE pg_default;

create trigger trg_art_posts_updated_at BEFORE
update on art_posts for EACH row
execute FUNCTION set_updated_at ();

create trigger trg_enforce_art_post_owner_match BEFORE INSERT
or
update on art_posts for EACH row
execute FUNCTION enforce_art_post_owner_match ();



-- ART REACTIONS

create table public.art_reactions (
  id uuid not null default gen_random_uuid (),
  post_id uuid not null,
  user_id uuid not null,
  reaction_type public.art_reaction_type not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint art_reactions_pkey primary key (id),
  constraint art_reactions_post_id_fkey foreign KEY (post_id) references art_posts (id) on delete CASCADE,
  constraint art_reactions_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_art_reactions_post_user on public.art_reactions using btree (post_id, user_id) TABLESPACE pg_default;

create index IF not exists idx_art_reactions_post_id on public.art_reactions using btree (post_id) TABLESPACE pg_default;

create index IF not exists idx_art_reactions_user_id on public.art_reactions using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_art_reactions_type on public.art_reactions using btree (reaction_type) TABLESPACE pg_default;

create trigger trg_art_reactions_sync_counts_delete
after DELETE on art_reactions for EACH row
execute FUNCTION sync_art_post_vote_counts_incremental ();

create trigger trg_art_reactions_sync_counts_insert
after INSERT on art_reactions for EACH row
execute FUNCTION sync_art_post_vote_counts_incremental ();

create trigger trg_art_reactions_sync_counts_update
after
update on art_reactions for EACH row
execute FUNCTION sync_art_post_vote_counts_incremental ();

create trigger trg_art_reactions_updated_at BEFORE
update on art_reactions for EACH row
execute FUNCTION set_updated_at ();


-- ART SIMILARITY SCANS

create table public.art_similarity_scans (
  id uuid not null default gen_random_uuid (),
  art_id uuid not null,
  owner_id uuid not null,
  status text not null default 'pending'::text,
  filename text null,
  original_hash text null,
  success boolean not null default false,
  total_matches integer not null default 0,
  best_source text null,
  best_link text null,
  best_url text null,
  best_match_pair text null,
  best_similarity_percentage numeric(5, 2) null,
  best_min_combined_distance numeric(10, 4) null,
  best_average_combined_distance numeric(10, 4) null,
  best_max_combined_distance numeric(10, 4) null,
  matches jsonb not null default '[]'::jsonb,
  hashes jsonb null,
  raw_response jsonb null,
  error_message text null,
  started_at timestamp with time zone null,
  completed_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint art_similarity_scans_pkey primary key (id),
  constraint uq_art_similarity_scans_art_id unique (art_id),
  constraint art_similarity_scans_art_id_fkey foreign KEY (art_id) references registered_arts (id) on delete CASCADE,
  constraint art_similarity_scans_owner_id_fkey foreign KEY (owner_id) references users (id) on delete CASCADE,
  constraint art_similarity_scans_best_similarity_percentage_check check (
    (
      (best_similarity_percentage is null)
      or (
        (best_similarity_percentage >= (0)::numeric)
        and (best_similarity_percentage <= (100)::numeric)
      )
    )
  ),
  constraint art_similarity_scans_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'running'::text,
          'completed'::text,
          'failed'::text,
          'cancelled'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_owner_id on public.art_similarity_scans using btree (owner_id) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_status on public.art_similarity_scans using btree (status) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_success on public.art_similarity_scans using btree (success) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_best_similarity on public.art_similarity_scans using btree (best_similarity_percentage desc) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_best_source on public.art_similarity_scans using btree (best_source) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_created_at on public.art_similarity_scans using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_matches_gin on public.art_similarity_scans using gin (matches jsonb_path_ops) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_raw_response_gin on public.art_similarity_scans using gin (raw_response jsonb_path_ops) TABLESPACE pg_default;

create index IF not exists idx_art_similarity_scans_hashes_gin on public.art_similarity_scans using gin (hashes jsonb_path_ops) TABLESPACE pg_default;

create trigger trg_art_similarity_scans_updated_at BEFORE
update on art_similarity_scans for EACH row
execute FUNCTION set_updated_at ();

create trigger trg_notify_art_similarity_scan_status
after
update on art_similarity_scans for EACH row
execute FUNCTION notify_art_similarity_scan_status ();


-- GENRES

create table public.genres (
  id smallint generated always as identity not null,
  name text not null,
  constraint genres_pkey primary key (id),
  constraint genres_name_key unique (name)
) TABLESPACE pg_default;



-- NOTIFICATIONS

create table public.notifications (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  type text not null,
  title text not null,
  message text not null,
  related_art_id uuid null,
  related_report_id uuid null,
  related_scan_id uuid null,
  action_url text null,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  read_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint notifications_pkey primary key (id),
  constraint notifications_related_art_id_fkey foreign KEY (related_art_id) references registered_arts (id) on delete CASCADE,
  constraint notifications_related_report_id_fkey foreign KEY (related_report_id) references reports (id) on delete CASCADE,
  constraint notifications_related_scan_id_fkey foreign KEY (related_scan_id) references art_similarity_scans (id) on delete CASCADE,
  constraint notifications_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE,
  constraint notifications_type_check check (
    (
      type = any (
        array[
          'artwork_registered'::text,
          'scan_completed'::text,
          'scan_flagged'::text,
          'scan_failed'::text,
          'report_submitted'::text,
          'report_resolved'::text,
          'blockchain_recorded'::text,
          'system_announcement'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_notifications_report_event on public.notifications using btree (user_id, related_report_id, type) TABLESPACE pg_default
where
  (related_report_id is not null);

create unique INDEX IF not exists uq_notifications_scan_event on public.notifications using btree (user_id, related_scan_id, type) TABLESPACE pg_default
where
  (related_scan_id is not null);

create index IF not exists idx_notifications_user_id on public.notifications using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_notifications_user_created_at on public.notifications using btree (user_id, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_notifications_user_is_read on public.notifications using btree (user_id, is_read) TABLESPACE pg_default;

create index IF not exists idx_notifications_user_unread_created_at on public.notifications using btree (user_id, is_read, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_notifications_type on public.notifications using btree (type) TABLESPACE pg_default;

create index IF not exists idx_notifications_related_art_id on public.notifications using btree (related_art_id) TABLESPACE pg_default;

create index IF not exists idx_notifications_related_report_id on public.notifications using btree (related_report_id) TABLESPACE pg_default;

create index IF not exists idx_notifications_related_scan_id on public.notifications using btree (related_scan_id) TABLESPACE pg_default;

create unique INDEX IF not exists uq_notifications_blockchain_event on public.notifications using btree (user_id, related_art_id, type) TABLESPACE pg_default
where
  (
    (type = 'blockchain_recorded'::text)
    and (related_art_id is not null)
  );



-- REGISTERED ARTS

create table public.registered_arts (
  id uuid not null default gen_random_uuid (),
  owner_id uuid not null,
  title text not null,
  description text null,
  c_asset_id text null,
  c_secure_url text null,
  file_hash text not null,
  perceptual_hash text not null,
  author_id_hash text null,
  evidence_hash text null,
  evidence jsonb null,
  chain text null,
  tx_hash text null,
  block_number bigint null,
  work_id text null,
  status public.art_status not null default 'pending_blockchain'::art_status,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  plagiarism_hashes json null,
  constraint registered_arts_pkey primary key (id),
  constraint registered_arts_tx_hash_key unique (tx_hash),
  constraint registered_arts_owner_id_fkey foreign KEY (owner_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_owner on public.registered_arts using btree (owner_id) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_status on public.registered_arts using btree (status) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_created_at on public.registered_arts using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_file_hash on public.registered_arts using btree (file_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_phash on public.registered_arts using btree (perceptual_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_work_id on public.registered_arts using btree (work_id) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_author_id_hash on public.registered_arts using btree (author_id_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_evidence_hash on public.registered_arts using btree (evidence_hash) TABLESPACE pg_default;

create unique INDEX IF not exists uq_registered_arts_owner_file on public.registered_arts using btree (owner_id, file_hash) TABLESPACE pg_default;

create index IF not exists idx_registered_arts_tx_hash on public.registered_arts using btree (tx_hash) TABLESPACE pg_default;

create trigger trg_notify_artwork_registered
after INSERT on registered_arts for EACH row
execute FUNCTION notify_artwork_registered ();

create trigger trg_notify_blockchain_recorded
after
update on registered_arts for EACH row
execute FUNCTION notify_blockchain_recorded ();

create trigger trg_registered_arts_updated_at BEFORE
update on registered_arts for EACH row
execute FUNCTION set_updated_at ();



-- REPORTS

create table public.reports (
  id uuid not null default gen_random_uuid (),
  reporter_id uuid not null,
  reported_art_post_id uuid not null,
  report_type public.report_type not null,
  title text not null,
  description text not null,
  status public.report_status not null default 'open'::report_status,
  created_at timestamp with time zone not null default now(),
  resolved_at timestamp with time zone null,
  constraint reports_pkey primary key (id),
  constraint reports_reported_art_post_id_fkey foreign KEY (reported_art_post_id) references art_posts (id),
  constraint reports_reporter_id_fkey foreign KEY (reporter_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_reports_status on public.reports using btree (status) TABLESPACE pg_default;

create index IF not exists idx_reports_reported_art_id on public.reports using btree (reported_art_post_id) TABLESPACE pg_default;

create index IF not exists idx_reports_reporter_id on public.reports using btree (reporter_id) TABLESPACE pg_default;

create index IF not exists idx_reports_created_at on public.reports using btree (created_at desc) TABLESPACE pg_default;

create trigger trg_notify_report_resolved
after
update on reports for EACH row
execute FUNCTION notify_report_resolved ();

create trigger trg_notify_report_submitted_to_admins
after INSERT on reports for EACH row
execute FUNCTION notify_report_submitted_to_admins ();

create trigger trg_notify_report_submitted_to_reporter
after INSERT on reports for EACH row
execute FUNCTION notify_report_submitted_to_reporter ();



-- USERS

create table public.users (
  id uuid not null,
  full_name text not null,
  username public.citext not null,
  bio text null,
  c_profile_image text null,
  role public.user_role not null default 'user'::user_role,
  last_active timestamp with time zone not null default now(),
  is_online boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  email text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_username_key unique (username),
  constraint users_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint username_len check (
    (
      (char_length((username)::text) >= 3)
      and (char_length((username)::text) <= 30)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_users_username on public.users using btree (username) TABLESPACE pg_default;

create index IF not exists idx_users_role on public.users using btree (role) TABLESPACE pg_default;

create index IF not exists idx_users_last_active on public.users using btree (last_active desc) TABLESPACE pg_default;

create trigger trg_users_updated_at BEFORE
update on users for EACH row
execute FUNCTION set_updated_at ();